# Generated by Django 5.0.4 on 2024-04-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imo_number', models.CharField(max_length=10, unique=True)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
    ]
