# Generated by Django 5.0.4 on 2024-04-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vessel',
            name='principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='vessels.principal'),
            preserve_default=False,
        ),
    ]
