# Generated by Django 5.0.4 on 2024-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_principal_vessel_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='contact_details',
        ),
    ]
