# Generated by Django 5.0.4 on 2024-04-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_remove_principal_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='imo_number',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='owner',
        ),
        migrations.AddField(
            model_name='principal',
            name='contact_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vessel',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.principal'),
        ),
    ]
