# Generated by Django 5.0.4 on 2024-04-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspection_type', models.CharField(max_length=255)),
                ('report', models.TextField()),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.vessel')),
            ],
        ),
    ]
