# Generated by Django 5.0.4 on 2024-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_section_options_section_order_question_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.CharField(choices=[('NA', 'N/A'), ('NV', 'N/V'), ('YES', 'Yes'), ('NO', 'No')], default='NA', max_length=3),
        ),
    ]
