# Generated by Django 5.0.4 on 2024-04-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_comment_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='inspection_version',
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspections.inspectiontemplate'),
        ),
        migrations.AddField(
            model_name='section',
            name='inspection_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inspections.inspectiontemplate'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InspectionVersion',
        ),
    ]
