# Generated by Django 5.0.4 on 2024-04-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspectiontemplate_remove_section_inspection_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='inspection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inspections.inspection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_comments', to='inspections.question'),
        ),
    ]
