# Generated by Django 5.0.4 on 2024-04-05 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_comment_inspection_alter_comment_question'),
        ('vessels', '0004_remove_vessel_imo_number_remove_vessel_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order_for_inspector', 'order_for_customer']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='order_for_customer',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='order_for_inspector',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_inspections', to='inspections.inspectiontemplate'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vessels.vessel'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.question')),
            ],
        ),
    ]
