# Generated by Django 5.0.4 on 2024-04-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectiontemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='comment_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_for_customer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_for_inspector',
        ),
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title',
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='comments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='question',
            name='inspection_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='inspections.inspectiontemplate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inspections.question'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspections.inspectiontemplate'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
