# Generated by Django 5.0.4 on 2024-04-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_alter_inspectiontemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='question',
            name='inspection_template',
        ),
        migrations.AddField(
            model_name='question',
            name='comment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='order_for_customer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order_for_inspector',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.CharField(choices=[('NA', 'N/A'), ('NV', 'N/V'), ('YES', 'Yes'), ('NO', 'No')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inspections.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_inspections', to='inspections.inspectiontemplate'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.question')),
            ],
        ),
    ]
