# Generated by Django 5.0.4 on 2024-04-05 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_remove_question_inspection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_responses/')),
                ('additional_comment', models.TextField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.question')),
            ],
        ),
    ]
